version: "3.2"

services:
 nginx:
   image: nginx:alpine
   volumes:
     - ./var/www:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
   ports:
     - 80:80
     - 443:443
   depends_on:
     - php

 php:
   build:
     context: .
   volumes:
     - ./var/www:/var/www
   ports:
     - 9000:9000

 mysql:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: CY166wfj
       MYSQL_DATABASE: lab_laravel
       MYSQL_USER: krusx
       MYSQL_PASSWORD: CY166wfj
     ports:
       - 3307:3306